In [1]:
import pandas as pd 
import numpy as np


import scipy.cluster.hierarchy as sch

In [2]:
df  = pd.read_csv('symbols-correlation.csv', index_col = 'Symbol')
df.head()

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Symbol,,,,,,,,,,,,,,,,,,,,,
A,0,50,24,88,72,48,52,88,100,76,...,62,74,46,68,70,24,70,76,60,78
AAL,50,0,42,60,56,26,18,36,40,48,...,56,76,2,76,60,-6,38,32,74,38
AAP,24,42,0,46,62,12,16,20,36,22,...,36,48,28,70,60,8,24,22,48,22
AAPL,88,60,46,0,48,8,40,68,82,54,...,74,80,14,78,68,34,60,72,50,58
ABBV,72,56,62,48,0,50,84,78,94,54,...,26,58,48,62,56,16,58,44,68,56

In [3]:
def _clustering_pass(sub, is_corr , max_cluster = 10):
    df = sub.copy()
    
    if is_corr: 
        X = df.values
    else:
        X = df.corr().values
    d = sch.distance.pdist(X)
    L = sch.ward(d)
    ind = sch.fcluster(L, t = max_cluster, criterion ='maxclust')

    columns = [df.columns.tolist()[i] for i in list(np.argsort(ind))]
    df = df.reindex(columns, axis='columns')
    if is_corr: df = df.reindex(columns, axis='index')
    
    unique, counts = np.unique(ind, return_counts=True)
    counts = dict(zip(unique, counts))

    return (ind, counts, df)

In [4]:

def _clustering_pass(sub, is_corr , max_cluster = 10):
    df = sub.copy()
    
    if is_corr: 
        X = df.values
    else:
        X = df.corr().values
    d = sch.distance.pdist(X)
    L = sch.ward(d)
    ind = sch.fcluster(L, t = max_cluster, criterion ='maxclust')

    columns = [df.columns.tolist()[i] for i in list(np.argsort(ind))]
    df = df.reindex(columns, axis='columns')
    if is_corr: df = df.reindex(columns, axis='index')
    
    unique, counts = np.unique(ind, return_counts=True)
    counts = dict(zip(unique, counts))

    return (ind, counts, df)

In [5]:
index, counts ,df_ = _clustering_pass(df, is_corr=True , max_cluster = 20)
df_['Cluster'] = index
df_.to_csv('symbols-correlation-clusters.csv')

In [6]:
df_.head()

,DIS,ALLE,TGT,CMCSA,GD,TAP,MYL,T,NLSN,HST,...,ROL,LYV,EL,CRM,ATVI,VNO,LLY,FTNT,COST,Cluster
Symbol,,,,,,,,,,,,,,,,,,,,,
DIS,0,46,28,86,74,30,32,38,50,56,...,42,74,54,36,36,46,28,50,34,6
ALLE,46,0,8,50,24,44,36,30,40,82,...,24,60,52,28,52,58,14,30,30,7
TGT,28,8,0,38,36,42,4,28,18,30,...,30,8,28,22,22,6,34,22,70,1
CMCSA,86,50,38,0,74,50,54,68,66,40,...,50,86,64,56,30,38,30,26,44,6
GD,74,24,36,74,0,34,58,72,44,18,...,66,46,34,52,16,32,38,38,44,11