In [1]:
import pandas as pd 
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

Bad key "text.kerning_factor" on line 4 in
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution

In [2]:
df = pd.read_csv('stocks/total_data_price_Change_Symbol.csv', index_col = 'Symbol')
df.head()

,2019-01-31,2019-02-01,2019-02-04,2019-02-05,2019-02-06,2019-02-07,2019-02-08,2019-02-11,2019-02-12,2019-02-13,...,2019-12-17,2019-12-18,2019-12-19,2019-12-20,2019-12-23,2019-12-24,2019-12-26,2019-12-27,2019-12-30,2019-12-31
Symbol,,,,,,,,,,,,,,,,,,,,,
A,0.92,0.82,0.19,0.09,0.09,-0.23,-0.17,-0.07,0.57,0.48,...,-0.29,-0.09,0.02,0.41,0.61,0.26,0.09,0.05,-0.07,0.01
AAL,-0.26,-0.06,0.14,0.41,0.25,-0.17,-0.31,-0.06,-0.14,0.07,...,0.19,0.17,0.21,0.25,0.43,0.21,0.21,-0.29,-0.29,-0.33
AAP,1.44,1.21,0.77,0.75,-0.60,0.59,0.32,2.63,1.58,1.34,...,0.62,0.94,1.01,0.07,0.66,1.36,0.38,-0.54,-0.48,0.30
AAPL,3.31,3.87,1.96,2.53,2.52,-0.10,-0.99,-1.33,0.22,-0.08,...,2.97,1.52,0.05,-0.32,1.41,1.41,3.47,1.92,2.40,1.24
ABBV,0.96,0.93,-0.16,-0.18,-0.43,0.20,-0.01,0.21,0.23,0.34,...,0.44,0.48,-0.21,-0.26,0.30,0.35,0.17,-0.34,-0.43,-0.42

In [3]:
def calculate_timeseries_correlation(data):
    result = []
    days = data.shape[1]
    
    for i in range(len(data)):
        symbol_corr = []
        for j in range(len(data)):
            if i == j :
                symbol_corr.append(0)
                continue

            change = [1 if np.sign(data[i , day]) == np.sign(data[j , day])
                      else 0 if data[i , day] == 0 and data[j , day] == 0
                      else -1 
                      for day in range(days)]

            symbol_corr.append(sum(change))

        result.append(symbol_corr)
    return result

In [4]:
symbols = df.index
data = df.to_numpy()
correlation = calculate_timeseries_correlation(data)

In [9]:
df_corr = pd.DataFrame(correlation, columns = symbols , index = symbols) 
df_corr.head()
df_corr.to_csv('symbols-correlation.csv')

In [7]:
#for col in df_corr.columns:
#    print(col , df_corr[col].nlargest(3))